# Generated by Django 6.0.1 on 2026-01-13 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Expired', 'Expired')], max_length=20)),
                ('type', models.CharField(choices=[('Booking', 'Booking'), ('Cancellation fee', 'Cancellation Fee'), ('No show fee', 'No Show Fee'), ('Overstay fee', 'Overstay Fee')], max_length=20)),
                ('session_url', models.URLField()),
                ('session_id', models.CharField(max_length=255)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking')),
            ],
        ),
    ]
